In [3]:
import numpy as np

# Testing a little + trash can

In [17]:
data_1 = np.load("../data/scada_data_1.npz", allow_pickle=True)

In [18]:
print(data_1)

NpzFile '../data/scada_data_1.npz' with keys: sensor_readings, col_desc, sensor_readings_time, flow_unit


In [19]:
print(data_1["flow_unit"])

8


In [20]:
print(data_1["col_desc"])

[['pressure' '10' 'psi']
 ['pressure' '11' 'psi']
 ['pressure' '12' 'psi']
 ['pressure' '13' 'psi']
 ['pressure' '21' 'psi']
 ['pressure' '22' 'psi']
 ['pressure' '23' 'psi']
 ['pressure' '31' 'psi']
 ['pressure' '32' 'psi']
 ['pressure' '9' 'psi']
 ['pressure' '2' 'psi']
 ['flow' '10' 'cubic meter/hr']
 ['flow' '11' 'cubic meter/hr']
 ['flow' '12' 'cubic meter/hr']
 ['flow' '21' 'cubic meter/hr']
 ['flow' '22' 'cubic meter/hr']
 ['flow' '31' 'cubic meter/hr']
 ['flow' '110' 'cubic meter/hr']
 ['flow' '111' 'cubic meter/hr']
 ['flow' '112' 'cubic meter/hr']
 ['flow' '113' 'cubic meter/hr']
 ['flow' '121' 'cubic meter/hr']
 ['flow' '122' 'cubic meter/hr']
 ['flow' '9' 'cubic meter/hr']
 ['bulk_species_node' 'Chlorine @ 10' 'MG']
 ['bulk_species_node' 'Chlorine @ 11' 'MG']
 ['bulk_species_node' 'Chlorine @ 12' 'MG']
 ['bulk_species_node' 'Chlorine @ 13' 'MG']
 ['bulk_species_node' 'Chlorine @ 21' 'MG']
 ['bulk_species_node' 'Chlorine @ 22' 'MG']
 ['bulk_species_node' 'Chlorine @ 23' 'MG'

In [21]:
print(data_1["sensor_readings"])
#sensors 25-33 chlorine
#sensors 34-44 arsenic

[[126.85165  120.19229  117.086006 ...   0.         0.         0.      ]
 [127.79879  121.24273  118.18431  ...   0.         0.         0.      ]
 [128.83162  122.38834  119.31003  ...   0.         0.         0.      ]
 ...
 [133.22299  127.26107  125.39017  ...   0.         0.         0.      ]
 [120.56403  120.56403  125.185265 ...   0.         0.         0.      ]
 [119.99929  119.99929  124.55526  ...   0.         0.         0.      ]]


In [22]:
#get the indices/column numbers of the chlorine, flow, and arsenic sensors in the file

chlorine_sensors_indices = []
arsenic_sensors_indices = []
flow_sensors_indices = []
for i in range(0,len(data_1["col_desc"])):
    if "Chlorine" in data_1["col_desc"][i][1]:
        chlorine_sensors_indices.append(i)
    elif "AsIII" in data_1["col_desc"][i][1]:
        arsenic_sensors_indices.append(i)
    elif "flow" in data_1["col_desc"][i][0]:
        flow_sensors_indices.append(i)


In [23]:
chlorine_sensors_indices

[24, 25, 26, 27, 28, 29, 30, 31, 32]

In [24]:
print(data_1.files)

['sensor_readings', 'col_desc', 'sensor_readings_time', 'flow_unit']


In [25]:
#Get sensor readings of chlorine and flow sensors
cl_first = chlorine_sensors_indices[0]
cl_last = chlorine_sensors_indices[-1]
flow_first = flow_sensors_indices[0]
flow_last = flow_sensors_indices[-1]
cols = np.r_[cl_first:cl_last+1,
             flow_first:flow_last+1]
data_1_X_cl = data_1["sensor_readings"][:,cl_first:cl_last+1]
data_1_X_flow = data_1["sensor_readings"][:, flow_first:flow_last+1]

#first 9 columns in data_1 are chlorine sensors, the rest are flow sensors

In [26]:
#double check that amount of values is right
print(data_1_X_cl[0])
print(data_1_X_flow[0])

[0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 426.45697    307.60675     12.489316    59.691998    21.583134
   10.106865  -286.63446    100.92958    -10.2694235   -2.863221
   20.831396     1.5775098  426.45697  ]


In [27]:
as_first = arsenic_sensors_indices[0]
as_last = arsenic_sensors_indices[-1]
data_1_y = data_1["sensor_readings"][:, as_first:as_last+1]

In [28]:
print(data_1_y[0])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#Originally from cell 4, but replaced by function:


# for subdata in data:
#     all_cl_sensor_readings = []
#     for i in range (0, (NUMBER_CL_SENSORS)):
#         sensor_readings = subdata["X_cl_st"][:,i]
#         all_cl_sensor_readings.append(sensor_readings)
#     all_cl_sensor_readings = np.array(all_cl_sensor_readings)
#     subdata["all_cl_sensor_readings"] = all_cl_sensor_readings

# for subdata in data:
#     all_flow_sensor_readings = []
#     for i in range (0, (NUMBER_FLOW_SENSORS)):
#         sensor_readings = subdata["X_flow_st"][:,i]
#         all_flow_sensor_readings.append(sensor_readings)
#     all_flow_sensor_readings = np.array(all_flow_sensor_readings)
#     subdata["all_flow_sensor_readings"] = all_flow_sensor_readings

# Reading the files

In [ ]:
#Cell 1
data = []

#Iterate over the different numpy files
for i in range(1,21):
    chlorine_sensors = []
    flow_sensors = []
    arsenic_sensors = []
    X_cl = []
    X_flow = []
    y = []

    file_data = np.load(f"../data/scada_data_{i}.npz", allow_pickle=True)

    #Get the indices/column numbers of the chlorine, flow, and arsenic sensors in the file

    for j in range(0,len(file_data["col_desc"])):
        if "Chlorine" in file_data["col_desc"][j][1]:
            chlorine_sensors.append(j)
        elif "AsIII" in file_data["col_desc"][j][1]:
            arsenic_sensors.append(j)
        elif "flow" in file_data["col_desc"][j][0]:
            flow_sensors.append(j)

    #Get sensor readings of chlorine and flow sensors
    cl_first = chlorine_sensors[0]
    cl_last = chlorine_sensors[-1]
    flow_first = flow_sensors[0]
    flow_last = flow_sensors[-1]
    cols = np.r_[cl_first:cl_last+1,
                flow_first:flow_last+1]
    X_cl.append(file_data["sensor_readings"][:, cl_first:cl_last+1])
    X_flow.append(file_data["sensor_readings"][:, flow_first:flow_last+1])

    #Get sensor readings of arsenic sensors
    as_first = arsenic_sensors[0]
    as_last = arsenic_sensors[-1]
    y.append(file_data["sensor_readings"][:, as_first:as_last+1])

    data.append({"file": file_data, 
                 "Cl_sensors": chlorine_sensors, 
                 "Flow_sensors": flow_sensors, 
                 "As_sensors": arsenic_sensors, 
                 "X_cl": X_cl, 
                 "X_flow": X_flow, 
                 "y": y})

# Final remarks

Since all the values of each file are finally saved in various lists, inside a dictionary inside the data list, you have to cal them like this:

data[i]["xxxxxx"][0][j]

i is the file you want (counting starts at 0, so scada_data_1 is in data[0])  
"xxxxxx" is the part of the data you want  
Since every value is inside a list with one entry, you always have to use [0]  
j is the value/row (depending on the object)  
* for "file", "X_cl", "X_flow", and "y", it is the row
* for "Cl_sensors", "Flow_sensors", and "As_sensors", it is the value (there is only 1 row)

# Data standardization

    

In [ ]:
#Cell 2
#calculate means and standard deviations for chlorine, flow, and arsenic sensor readings across all files
cl_all = []
as_all = []
flow_all = []

for i in range(0,20):
    cl_all.append(data[i-1]["X_cl"][0])
    flow_all.append(data[i-1]["X_flow"][0])
    as_all.append(data[i-1]["y"][0])
    
cl_all = np.concatenate(cl_all, axis=0)
flow_all = np.concatenate(flow_all, axis=0)
as_all = np.concatenate(as_all, axis=0)
cl_mean = np.mean(cl_all)
flow_mean = np.mean(flow_all)
as_mean = np.mean(as_all)
cl_std = np.std(cl_all)
flow_std = np.std(flow_all)
as_std = np.std(as_all)

In [ ]:
#Cell 3
# standardize the chlorine, flow, and arsenic sensor readings in each file
# standardization formula: Z(t) = X(t) - µ / σ (Detecting Changes in Water Quality Data)

def standardize(unst_data, mean, std):
    st_data = np.zeros(unst_data.shape)
    for j in range(0, len(unst_data)):
        for k in range(0, len(unst_data[j])):
            st_data[j][k] = (unst_data[j][k] - mean) / std  
    return st_data

for i in range(0,20):
    
    X_cl_st = standardize(data[i]["X_cl"][0], cl_mean, cl_std)
    X_flow_st = standardize(data[i]["X_flow"][0], flow_mean, flow_std)
    y_st = standardize(data[i]["y"][0], as_mean, as_std)

    data[i]["X_cl_st"] = X_cl_st
    data[i]["X_flow_st"] = X_flow_st
    data[i]["y_st"] = y_st

# Linear predictor

Step-wise list:

* Implement the equation, without the coefficents (main part)
* Set window size (P), maybe 10?
* Implement the second algorithm mentioned (autocorrelation method of AR modeling, get unbiased coefficients)
* Combine the two algorithms

In [31]:
#Cell 4
#Get the values per chlorine and flow, and arsenic sensor
NUMBER_CL_SENSORS = len(chlorine_sensors)
NUMBER_FLOW_SENSORS = len(flow_sensors)
NUMBER_AS_SENSORS = len(arsenic_sensors) 

def get_readings_per_sensor(data, number_sensors, sensor_type):
    for subdata in data: 
        all_sensor_readings = []
        for i in range (0, (number_sensors)):
            sensor_readings = subdata[sensor_type][:,i]
            all_sensor_readings.append(sensor_readings)
        subdata[f"{sensor_type}_per_sensor"] = np.array(all_sensor_readings)
    
get_readings_per_sensor(data, NUMBER_CL_SENSORS, "X_cl_st")
get_readings_per_sensor(data, NUMBER_FLOW_SENSORS, "X_flow_st")
get_readings_per_sensor(data, NUMBER_AS_SENSORS, "y_st")

array([-0.10334692, -0.10334692, -0.10334692, ..., -0.10334692,
       -0.10334692, -0.10334692])